### ISSUE TITLE
Лаб1 Уфилин

### ISSUE THREAD

**Issue by Ideolion** [avalon-dev-j110/laboratornaya-rabota-no1-Ideolion#1]
Алексей, прошу посмотреть лабораторную работу 1.
Слушатель Уфилин Денис.
Я немного запутался с GIT, но думаю разберусь в дальнейшем.

**Comment by AlekseiMaslakov** [comment]
Здравствуйте
Вы запушили в репозиторий только Main.java, остальные файлы не загружены.

**Comment by Ideolion** [comment]
Добрый день! 
Кажется мне удалось загрузить все остальное.

**Comment by AlekseiMaslakov** [comment]
Здравствуйте
Принято, со следующей лабы отправляйте на проверку через pull request, пожалуйста.
